name: Generate Node Modules

on:
  push:
    branches:
      - gh-pages  # Adjust to match your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '9'  # Adjust to match your Node.js version

    - name: Install Dependencies
      run: |
        npm install
